#action.yml
name: patchwork-status

description: 'Report the Patchwork Bluetooth status'

inputs:
  github_token:
    description: Secret github github_token
    required: true
  email_token:
    description: Email github_token
    required: true
  patchwork_token:
    description: Patchwork access token
    required: true
  task:
    description: The name of the task to run.
    required: false
    default: 'status'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.task }}
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    EMAIL_TOKEN: ${{ inputs.email_token }}
    PATCHWORK_TOKEN: ${{ inputs.patchwork_token }}
