#action.yml
name: Checkpatch

description: 'Run checkpatch with patches'

inputs:
  github_token:
    description: Secret github github_token
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
